.TH xxvd 1 "July 14, 2007"  
.SH NAME
XXV \- (Xtreme eXtension for VDR) provides a central service to administer VDR
.SH SYNOPSIS
\fBxxvd\fR [\fB\-\-configfile=\fR \fBFILE\fR] [\fB\-\-logfile=\fR \fBFILE\fR] [\fB\-\-pidfile=\fR \fBFILE\fR] [\fB\-\-localedir=\fR \fBDIR\fR] [\fB\-\-moduledir=\fR \fBDIR\fR] [\fB\-\-docudir=\fR \fBDIR\fR] [\fB\-\-poddir=\fR \fBDIR\fR] [\fB\-\-htmldir=\fR \fBDIR\fR] [\fB\-\-fontdir=\fR \fBDIR\fR] [\fB\-\-vtxdir=\fR \fBDIR\fR] [\fB\-\-newsmods=\fR \fBDIR\fR] [\fB\-\-newstmpl=\fR \fBDIR\fR] [\fB\-\-kill\fR] [\fB\-\-verbose=\fR \fBLEVEL\fR] [\fB\-\-version\fR] [\fB\-\-nofork\fR]
.SH DESCRIPTION
\fBxxvd\fR is daemon behind XXV.
XXV provides a central service to administer VDR, it's contain 
a http daemon, a telnet server and a WAP server among other services.
And is extendable by plugins and skins. XXV allows to manage
timers, auto timers, channels, recordings and much more provided by VDR
.SH OPTIONS
.TP 
\-\-configfile=\fIFILE\fR
Use \fBFILE\fR as config file for XXV.
The config file is modified by XXV, so it shall not be read\-only.
.TP 
\-\-logfile=\fIFILE\fR.
Output all log messages to \fBFILE\fR.
.TP 
\-\-pidfile=\fIFILE\fR
Write process id of \fBxxvd\fR daemon to \fBFILE\fR.
.TP 
\-\-localedir=\fIDIR\fR
Search for locales in \fBDIR\fR. 
\fBDIR\fR should contain the typical locales structure
with XXV's translations. (eg. de/LC_MESSAGES/xxv.mo)
.TP 
\-\-moduledir=\fIDIR\fR
Search for modules (plugins) in \fBDIR\fR.
.TP 
\-\-docudir=\fIDIR\fR
Directory \fBDIR\fR with template files used for generate documentation.
.TP 
\-\-poddir=\fIDIR\fR
Generate the selfdocumentation files in \fBDIR\fR.
Documentation files are generated by XXV, so it shall be writable.
.TP 
\-\-htmldir=\fIDIR\fR
XXV searchs for it's html templates in \fBDIR\fR.
Each subdirectory in \fBDIR\fR is seen as a set of
templates (Skin).
.TP 
\-\-fontdir=\fIDIR\fR
XXV searchs usable fonts in \fBDIR\fR.
.TP 
\-\-vtxdir=\fIDIR\fR
XXV module VTX use font images from \fBDIR\fR.
.TP 
\-\-contrib=\fIDIR\fR
XXV use some external scripts in \fBDIR\fR.
.TP 
\-\-newsmods=\fIDIR\fR
\fBxxvd\fR search for news modules (news plugins) in \fBDIR\fR.
.TP 
\-\-newstmpl=\fIDIR\fR
XXV searches for news templates in \fBDIR\fR.
.TP 
\-\-kill
Kill daemon \fBxxvd\fR.
.TP 
\-\-verbose=\fILEVEL\fR
Select the verbose \fILEVEL\fR of the logged 
messages of XXV.
.RS 
.TP 0.2i
\(bu
0 \- Don't log messages
.TP 0.2i
\(bu
1 \- Errors only
.TP 0.2i
\(bu
2 \- Messages depends user action
.TP 0.2i
\(bu
3 \- More events
.TP 0.2i
\(bu
5 \- Lots of messages
.TP 0.2i
\(bu
>5 \- Messages with dump of caller stack
.RE
.TP 
\-\-version
Display the version number and exit.
.TP 
\-\-nofork
Debug mode: don't fork to the background.
.SH AUTHOR
This manual page was written by Tobias Grimm<tg@e\-tobi.net>.
.PP
(July 14, 2007)
